name: face_recognition
description: "Face detection app using YuNet model with OpenCV"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  opencv_dart: ^1.2.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/face_detection_yunet_2023mar.onnx
